package co.ats.wepapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FolderAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFolderAllPropertiesEquals(Folder expected, Folder actual) {
        assertFolderAutoGeneratedPropertiesEquals(expected, actual);
        assertFolderAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFolderAllUpdatablePropertiesEquals(Folder expected, Folder actual) {
        assertFolderUpdatableFieldsEquals(expected, actual);
        assertFolderUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFolderAutoGeneratedPropertiesEquals(Folder expected, Folder actual) {
        assertThat(actual)
            .as("Verify Folder auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFolderUpdatableFieldsEquals(Folder expected, Folder actual) {
        assertThat(actual)
            .as("Verify Folder relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getOrder()).as("check order").isEqualTo(expected.getOrder()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFolderUpdatableRelationshipsEquals(Folder expected, Folder actual) {
        // empty method
    }
}
